More generic and modern way to build package

diff --git a/make-package-debian b/make-package-debian
--- a/make-package-debian
+++ b/make-package-debian
@@ -2,44 +2,65 @@
 #
 # 2025/08/14 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
 
-trap '[ -n "${tmp_folder}" -a -d "${tmp_folder}" ] && rm -rf "${tmp_folder}"' QUIT
+set -euo pipefail
+
+# Clean at end of script in all case
+trap 'rm -rf "${tmp_folder:-}"' EXIT QUIT
 
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
 export LANG=C
 
+# Check build commands
+for cmd in ar tar gzip pod2man mktemp du cut install
+do
+  command -v "$cmd" >/dev/null || {
+    echo "error: $cmd missing"
+    exit 1
+  }
+done
+
+# Temporary folder
 tmp_folder=$(mktemp --directory /tmp/ocs-webutils-XXXXXX)
 { [ -n "${tmp_folder}" ] && [ -d "${tmp_folder}" ] ; } || exit 1
 
 # Set Name and Version
 PKG_NAME=ocs-webutils
-CODE_VERSION=$(grep '__version__' ocs-pkgpush | cut -f 2 -d '"') #'
+CODE_VERSION=$(./get-version)
 PKG_VERSION=1
+[ -n "${CODE_VERSION}" ] || {
+  echo "error: Empty version"
+  exit 1
+}
 
-# Create future tree
-mkdir -p "${tmp_folder}/usr/bin"
-mkdir -p ${tmp_folder}/usr/share/man/man1
-mkdir -p ${tmp_folder}/usr/share/ocs-utils
-mkdir -p ${tmp_folder}/etc/bash_completion.d
+# Transform version
+for f in ocs-pkgpush *.pod
+do
+  sed "s/@VERSION@/${CODE_VERSION}/g;" "${f}" > "${tmp_folder}/${f}"
+done
 
-# Documentations
-pod2man ocs-pkgpush.pod | gzip > "${tmp_folder}/usr/share/man/man1/ocs-pkgpush.1.gz"
-#pod2html --css podstyle.css --index --header ocs-pkgpush.pod > "${tmp_folder}/ocs-pkgpush.html"
+# Install files
+install -Dm 0755 -t "${tmp_folder}"/usr/bin/                "${tmp_folder}"/ocs-pkgpush
+install -Dm 0644 -t "${tmp_folder}"/usr/share/ocs-webutils/ LICENSE.md
+for script in ocs-pkgpush
+do
+  install -Dm 0644 "${script}".bash_completion "${tmp_folder}"/usr/share/bash-completion/completions/"${script}"
+done
 
-# Copy files
-cp ocs-pkgpush                  "${tmp_folder}/usr/bin/"
-#cp ocs-pkgpush.1.gz             "${tmp_folder}/usr/share/man/man1/"
-cp LICENSE.md                   "${tmp_folder}/usr/share/ocs-utils/"
-cp ocs-pkgpush.bash_completion  "${tmp_folder}/etc/bash_completion.d/"
-chmod -R a+rx        "${tmp_folder}/usr/bin/ocs-pkgpush"
-chmod -R a+rX,go-w   "${tmp_folder}/usr"
-chmod -R a+rX,go-w   "${tmp_folder}/etc"
+# Create manuals
+mkdir -p "${tmp_folder}"/usr/share/man/man1
+pod2man --section=1 --release="OCS-Webutils ${CODE_VERSION}" "${tmp_folder}"/ocs-pkgpush.pod | gzip > "${tmp_folder}"/usr/share/man/man1/ocs-pkgpush.1.gz
+
+# Good right
+chmod -R a+rX,go-w   "${tmp_folder}"/usr
+
+# Package size
+PKG_SIZE=$(du -ks "${tmp_folder}"/usr | cut -f 1)
 
 # Data archive
-rm -f "${tmp_folder}/data.tar.gz"
-(cd ${tmp_folder}; tar --owner root --group root -czf data.tar.gz ./usr ./etc)
+(cd "${tmp_folder}" || exit 1; tar --owner root --group root -czf data.tar.gz ./usr)
 
 # Control file
-cat <<END > "${tmp_folder}/control"
+cat <<END > "${tmp_folder}"/control
 Package: ${PKG_NAME}
 Version: ${CODE_VERSION}-${PKG_VERSION}
 Section: utils
@@ -48,7 +69,7 @@ Priority: optional
 Depends: python3 (>= 3.9), python3-venv, python3-pip, ca-certificates
 Recommends: python3-dev, build-essential
 Architecture: all
-Installed-Size: $(du -ks "${tmp_folder}"|cut -f 1)
+Installed-Size: ${PKG_SIZE}
 Maintainer: Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
 Description: Push packages to OCS Inventory via web interface automation
  This tool automates the process of uploading a package to an OCS Inventory
@@ -59,20 +80,21 @@ Homepage: https://gricad-gitlab.univ-grenoble-alpes.fr/legi/soft/trokata/ocs-web
 END
 
 # Control archive
-rm -f "${tmp_folder}/control.tar.gz"
-(cd "${tmp_folder}"; tar --owner root --group root -czf control.tar.gz control)
+(cd "${tmp_folder}" || exit 1; tar --owner root --group root -czf control.tar.gz control)
 
 # Format deb package
-echo 2.0 > "${tmp_folder}/debian-binary"
+echo 2.0 > "${tmp_folder}"/debian-binary
 
 # Create package (control before data)
-ar -r "${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb" "${tmp_folder}/debian-binary" "${tmp_folder}/control.tar.gz" "${tmp_folder}/data.tar.gz"
+ar -r "${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}"_all.deb "${tmp_folder}"/debian-binary "${tmp_folder}"/control.tar.gz "${tmp_folder}"/data.tar.gz
       
 # Clean
 rm -rf "${tmp_folder}"
 
 # Prepare reprepro upload
 echo "# Prepare reprepro upload"
-echo "( cd /srv/www/debian/ ; reprepro includedeb bookworm ~/bookworm/${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb )"
-echo "( cd /srv/www/debian/ ; reprepro includedeb trixie     ~/trixie/${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb )"
-echo "( cd /srv/www/debian/ ; reprepro dumpreferences ) | grep -i ocs-webutils"
+for dist in buster bullseye bookworm trixie
+do
+  echo "( cd /srv/www/debian/ || exit 1; reprepro includedeb '${dist}' ~/${dist}/${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb )"
+done
+echo "( cd /srv/www/debian/ ; reprepro dumpreferences ) | grep -i -- 'ocs-webutils'"
